<a href="https://colab.research.google.com/github/JuniorTorresMTJ/temp/blob/main/Proc_medico.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas            as pd
import numpy             as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn           as sns

In [ ]:
pd.options.display.float_format ="{:.2f}".format

In [ ]:
cols = ['Unidade da Federação', '02 Procedimentos com finalidade diagnóstica',
       '03 Procedimentos clínicos', '04 Procedimentos cirúrgicos',
       '05 Transplantes de orgãos, tecidos e células']

In [ ]:
df_out = pd.read_csv("/content/Proc_Out.csv", encoding="ISO-8859-1", 
            skiprows=4,skipfooter = 12, sep=";", thousands=".", decimal =",", usecols =cols)
df_nov = pd.read_csv("/content/Proc_Nov.csv", encoding="ISO-8859-1", 
            skiprows=4,skipfooter = 12, sep=";", thousands=".", decimal =",", usecols =cols)
df_dez = pd.read_csv("/content/Proc_Dez.csv", encoding="ISO-8859-1", 
            skiprows=4,skipfooter = 12, sep=";", thousands=".", decimal =",", usecols =cols)
df_jan = pd.read_csv("/content/Proc_Jan.csv", encoding="ISO-8859-1", 
            skiprows=4,skipfooter = 12, sep=";", thousands=".", decimal =",", usecols =cols)
df_fev = pd.read_csv("/content/Proc_Fev.csv", encoding="ISO-8859-1", 
            skiprows=4,skipfooter = 12, sep=";", thousands=".", decimal =",", usecols =cols)
df_mar = pd.read_csv("/content/Proc_Mar.csv", encoding="ISO-8859-1", 
            skiprows=4,skipfooter = 12, sep=";", thousands=".", decimal =",", usecols =cols)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:12: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  if sys.path[0] == '':

In [ ]:
s_out =pd.Series(['2020/Out', '2020/Out', '2020/Out', '2020/Out'])
s_nov =pd.Series(['2020/Nov', '2020/Nov', '2020/Nov', '2020/Nov'])
s_dez =pd.Series(['2020/Dez', '2020/Dez', '2020/Dez', '2020/Dez'])
s_jan =pd.Series(['2021/Jan', '2021/Jan', '2021/Jan', '2021/Jan'])
s_fev =pd.Series(['2021/Fev', '2021/Fev', '2021/Fev', '2021/Fev'])
s_mar =pd.Series(['2021/Mar', '2021/Mar', '2021/Mar', '2021/Mar'])

In [ ]:
df_out['mes'] = s_out
df_nov['mes'] = s_nov
df_dez['mes'] = s_dez
df_jan['mes'] = s_jan
df_fev['mes'] = s_fev
df_mar['mes'] = s_mar

In [ ]:
proc_medico  =  pd.concat([df_out, df_nov,df_dez, df_jan, df_fev, df_mar])
proc_medico

  Unidade da Federação  ...       mes
0        26 Pernambuco  ...  2020/Out
1      31 Minas Gerais  ...  2020/Out
2    33 Rio de Janeiro  ...  2020/Out
3         35 São Paulo  ...  2020/Out
0        26 Pernambuco  ...  2020/Nov
1      31 Minas Gerais  ...  2020/Nov
2    33 Rio de Janeiro  ...  2020/Nov
3         35 São Paulo  ...  2020/Nov
0        26 Pernambuco  ...  2020/Dez
1      31 Minas Gerais  ...  2020/Dez
2    33 Rio de Janeiro  ...  2020/Dez
3         35 São Paulo  ...  2020/Dez
0        26 Pernambuco  ...  2021/Jan
1      31 Minas Gerais  ...  2021/Jan
2    33 Rio de Janeiro  ...  2021/Jan
3         35 São Paulo  ...  2021/Jan
0        26 Pernambuco  ...  2021/Fev
1      31 Minas Gerais  ...  2021/Fev
2    33 Rio de Janeiro  ...  2021/Fev
3         35 São Paulo  ...  2021/Fev
0        26 Pernambuco  ...  2021/Mar
1      31 Minas Gerais  ...  2021/Mar
2    33 Rio de Janeiro  ...  2021/Mar
3         35 São Paulo  ...  2021/Mar

[24 rows x 6 columns]

In [ ]:
proc_medico['id_uf'] = proc_medico["Unidade da Federação"].str.slice(0,3)
proc_medico

  Unidade da Federação  ...  id_uf
0        26 Pernambuco  ...    26
1      31 Minas Gerais  ...    31
2    33 Rio de Janeiro  ...    33
3         35 São Paulo  ...    35
0        26 Pernambuco  ...    26
1      31 Minas Gerais  ...    31
2    33 Rio de Janeiro  ...    33
3         35 São Paulo  ...    35
0        26 Pernambuco  ...    26
1      31 Minas Gerais  ...    31
2    33 Rio de Janeiro  ...    33
3         35 São Paulo  ...    35
0        26 Pernambuco  ...    26
1      31 Minas Gerais  ...    31
2    33 Rio de Janeiro  ...    33
3         35 São Paulo  ...    35
0        26 Pernambuco  ...    26
1      31 Minas Gerais  ...    31
2    33 Rio de Janeiro  ...    33
3         35 São Paulo  ...    35
0        26 Pernambuco  ...    26
1      31 Minas Gerais  ...    31
2    33 Rio de Janeiro  ...    33
3         35 São Paulo  ...    35

[24 rows x 7 columns]

In [ ]:
proc_medico["Unidade da Federação"] = proc_medico["Unidade da Federação"].str.slice(3,)
proc_medico.head()

  Unidade da Federação  ...  id_uf
0           Pernambuco  ...    26
1         Minas Gerais  ...    31
2       Rio de Janeiro  ...    33
3            São Paulo  ...    35
0           Pernambuco  ...    26

[5 rows x 7 columns]

In [ ]:
proc_medico.to_csv(index=False)

'Unidade da Federação,02 Procedimentos com finalidade diagnóstica,03 Procedimentos clínicos,04 Procedimentos cirúrgicos,"05 Transplantes de orgãos, tecidos e células",mes,id_uf\nPernambuco,54683.78,30791442.41,31934159.28,3775342.78,2020/Out,26 \nMinas Gerais,233935.0,99699818.21,72911481.06,5433918.47,2020/Out,31 \nRio de Janeiro,77152.37,45882254.46,37733344.88,3302897.64,2020/Out,33 \nSão Paulo,297141.46,189960681.56,133815665.85,21659579.92,2020/Out,35 \nPernambuco,34856.75,41629513.31,32540702.39,4699103.76,2020/Nov,26 \nMinas Gerais,301966.95,94350329.53,75352874.73,5248055.7,2020/Nov,31 \nRio de Janeiro,76377.5,47380960.47,35767029.23,3552133.77,2020/Nov,33 \nSão Paulo,340477.41,175121295.2,138307657.46,21315435.59,2020/Nov,35 \nPernambuco,44592.5,39447624.03,28444800.28,3041035.34,2020/Dez,26 \nMinas Gerais,335335.78,95342051.54,72280260.58,4551787.72,2020/Dez,31 \nRio de Janeiro,61747.42,52619052.35,36017054.0,1718872.18,2020/Dez,33 \nSão Paulo,342126.99,180827685.68,130495969.68,18823263.63,2020/Dez,35 \nPernambuco,38614.86,52172898.74,27890525.89,3744182.95,2021/Jan,26 \nMinas Gerais,260827.45,104478526.18,65931950.41,4050857.94,2021/Jan,31 \nRio de Janeiro,62309.53,60264102.3,31742166.71,2111095.88,2021/Jan,33 \nSão Paulo,463038.21,206234942.85,128898206.79,19553337.75,2021/Jan,35 \nPernambuco,40057.44,45656209.31,26723691.71,3142706.23,2021/Fev,26 \nMinas Gerais,175800.68,103871660.86,68653242.18,4569990.62,2021/Fev,31 \nRio de Janeiro,46623.22,54125750.05,29541923.42,1869261.26,2021/Fev,33 \nSão Paulo,364815.95,200506338.47,127969513.03,19986463.54,2021/Fev,35 \nPernambuco,50805.83,52747229.07,27275410.58,3797547.25,2021/Mar,26 \nMinas Gerais,359439.54,127036243.04,68727564.39,4347798.1,2021/Mar,31 \nRio de Janeiro,60183.42,69746070.16,35171962.59,1859079.64,2021/Mar,33 \nSão Paulo,296235.55,252233186.99,120770068.89,19646655.99,2021/Mar,35 \n'

In [ ]:
proc_medico

  Unidade da Federação  ...  id_uf
0           Pernambuco  ...    26
1         Minas Gerais  ...    31
2       Rio de Janeiro  ...    33
3            São Paulo  ...    35
0           Pernambuco  ...    26
1         Minas Gerais  ...    31
2       Rio de Janeiro  ...    33
3            São Paulo  ...    35
0           Pernambuco  ...    26
1         Minas Gerais  ...    31
2       Rio de Janeiro  ...    33
3            São Paulo  ...    35
0           Pernambuco  ...    26
1         Minas Gerais  ...    31
2       Rio de Janeiro  ...    33
3            São Paulo  ...    35
0           Pernambuco  ...    26
1         Minas Gerais  ...    31
2       Rio de Janeiro  ...    33
3            São Paulo  ...    35
0           Pernambuco  ...    26
1         Minas Gerais  ...    31
2       Rio de Janeiro  ...    33
3            São Paulo  ...    35

[24 rows x 7 columns]

In [4]:
cols2 = ['UF [-]','Popula&ccedil;&atilde;o estimada - pessoas [2020]',
         'IDH &lt;span&gt;IÌndice de desenvolvimento humano&lt;/span&gt; [2010]',
         'Densidade demogr&aacute;fica - hab/km&sup2; [2010]']

In [5]:
data = pd.read_csv("/content/5d767af66c70a9c5c9e36d12c65d9647.csv", skipfooter = 2, encoding="ISO-8859-1",skiprows=1, thousands=".", decimal =",",usecols=cols2 )

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

In [6]:
data

                   UF [-]  ...  IDH &lt;span&gt;IÌndice de desenvolvimento humano&lt;/span&gt; [2010]
0                    Acre  ...                                                663
1                 Alagoas  ...                                                631
2            Amap&aacute;  ...                                                708
3                Amazonas  ...                                                674
4                   Bahia  ...                                                660
5            Cear&aacute;  ...                                                682
6        Distrito Federal  ...                                                824
7   Esp&iacute;rito Santo  ...                                                740
8            Goi&aacute;s  ...                                                735
9         Maranh&atilde;o  ...                                                639
10            Mato Grosso  ...                                                725
11     Mato Grosso do Sul  ...                                                729
12           Minas Gerais  ...                                                731
13            Par&aacute;  ...                                                646
14         Para&iacute;ba  ...                                                658
15          Paran&aacute;  ...                                                749
16             Pernambuco  ...                                                673
17           Piau&iacute;  ...                                                646
18         Rio de Janeiro  ...                                                761
19    Rio Grande do Norte  ...                                                684
20      Rio Grande do Sul  ...                                                746
21         Rond&ocirc;nia  ...                                                690
22                Roraima  ...                                                707
23         Santa Catarina  ...                                                774
24       S&atilde;o Paulo  ...                                                783
25                Sergipe  ...                                                665
26              Tocantins  ...                                                699

[27 rows x 4 columns]

In [7]:
data.rename(columns={'UF [-]':'Unidade da Federação','Popula&ccedil;&atilde;o estimada - pessoas [2020]': 'População estimada/2020',
                     'Densidade demogr&aacute;fica - hab/km&sup2; [2010]':'Densidade demografica',
                     'IDH &lt;span&gt;IÌndice de desenvolvimento humano&lt;/span&gt; [2010]':'IDH'}, inplace = True)

In [10]:
data.to_csv(index=False)

'Unidade da Federação,População estimada/2020,Densidade demografica,IDH\nAcre,894470,447,663\nAlagoas,3351543,11233,631\nAmap&aacute;,861773,469,708\nAmazonas,4207714,223,674\nBahia,14930634,2482,660\nCear&aacute;,9187103,5676,682\nDistrito Federal,3055149,44466,824\nEsp&iacute;rito Santo,4064052,7625,740\nGoi&aacute;s,7113540,1765,735\nMaranh&atilde;o,7114598,1981,639\nMato Grosso,3526220,336,725\nMato Grosso do Sul,2809394,686,729\nMinas Gerais,21292666,3341,731\nPar&aacute;,8690745,607,646\nPara&iacute;ba,4039277,6670,658\nParan&aacute;,11516840,5240,749\nPernambuco,9616621,8962,673\nPiau&iacute;,3281480,1240,646\nRio de Janeiro,17366189,36523,761\nRio Grande do Norte,3534165,5999,684\nRio Grande do Sul,11422973,3796,746\nRond&ocirc;nia,1796460,658,690\nRoraima,631181,201,707\nSanta Catarina,7252502,6527,774\nS&atilde;o Paulo,46289333,16623,783\nSergipe,2318822,9436,665\nTocantins,1590248,498,699\n'

In [13]:
geo = pd.read_csv("/content/geo1.csv", encoding='utf8', thousands=".", decimal =",")

In [14]:
geo

   Unidade da Federação  População estimada/2020  Densidade demografica  IDH
0                  Acre                   894470                    447  663
1               Alagoas                  3351543                  11233  631
2                 Amapá                   861773                    469  708
3              Amazonas                  4207714                    223  674
4                 Bahia                 14930634                   2482  660
5                 Ceará                  9187103                   5676  682
6      Distrito Federal                  3055149                  44466  824
7        Espírito Santo                  4064052                   7625  740
8                 Goiás                  7113540                   1765  735
9              Maranhão                  7114598                   1981  639
10          Mato Grosso                  3526220                    336  725
11   Mato Grosso do Sul                  2809394                    686  729
12         Minas Gerais                 21292666                   3341  731
13                 Pará                  8690745                    607  646
14              Paraíba                  4039277                   6670  658
15               Paraná                 11516840                   5240  749
16           Pernambuco                  9616621                   8962  673
17                Piauí                  3281480                   1240  646
18       Rio de Janeiro                 17366189                  36523  761
19  Rio Grande do Norte                  3534165                   5999  684
20    Rio Grande do Sul                 11422973                   3796  746
21             Rondônia                  1796460                    658  690
22              Roraima                   631181                    201  707
23       Santa Catarina                  7252502                   6527  774
24            São Paulo                 46289333                  16623  783
25              Sergipe                  2318822                   9436  665
26            Tocantins                  1590248                    498  699

In [15]:
procedimentos = pd.read_csv("/content/procedimento_medicos.csv", encoding='utf8', thousands=".", decimal =",")

In [16]:
procedimentos

   Unidade da Federação  ...  id_uf
0            Pernambuco  ...     26
1          Minas Gerais  ...     31
2        Rio de Janeiro  ...     33
3             São Paulo  ...     35
4            Pernambuco  ...     26
5          Minas Gerais  ...     31
6        Rio de Janeiro  ...     33
7             São Paulo  ...     35
8            Pernambuco  ...     26
9          Minas Gerais  ...     31
10       Rio de Janeiro  ...     33
11            São Paulo  ...     35
12           Pernambuco  ...     26
13         Minas Gerais  ...     31
14       Rio de Janeiro  ...     33
15            São Paulo  ...     35
16           Pernambuco  ...     26
17         Minas Gerais  ...     31
18       Rio de Janeiro  ...     33
19            São Paulo  ...     35
20           Pernambuco  ...     26
21         Minas Gerais  ...     31
22       Rio de Janeiro  ...     33
23            São Paulo  ...     35

[24 rows x 7 columns]

In [20]:
procedimentos.groupby(['Unidade da Federação']).sum()

                      02 Procedimentos com finalidade diagnóstica  ...  id_uf
Unidade da Federação                                               ...
Minas Gerais                                            145676390  ...    186
Pernambuco                                               22347791  ...    156
Rio de Janeiro                                           31565371  ...    198
São Paulo                                               210383557  ...    210

[4 rows x 5 columns]

In [41]:
obt = pd.read_csv("/content/óbitos.csv", encoding='ISO-8859-1', skiprows=3,skipfooter = 12, sep=";")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

In [42]:
obt.drop(columns=['2008/Jan',	'2011/Abr',	'2012/Ago',	'2013/Jan',	'2016/Mar',	'2016/Abr',	'2017/Jan',	'2017/Mar',
         '2018/Out',	'2018/Dez',	'2019/Abr',	'2019/Mai',	'2020/Abr',	'2020/Jun',	'2020/Jul',	'2020/Ago',
         	'2020/Set',	'2020/Out'], axis=1)

      Unidade da Federação 2020/Nov  2020/Dez  ...  2021/Fev  2021/Mar  Total
0              11 Rondônia        6        46  ...       175       268    562
1                  12 Acre        2        17  ...        73        66    199
2              13 Amazonas        5       106  ...       432       330   1823
3               14 Roraima        1         5  ...       107       161    292
4                  15 Pará       16        91  ...       418       561   1304
5                 16 Amapá        1         7  ...        45        89    185
6             17 Tocantins        -         2  ...         7        50     61
7              21 Maranhão        8        75  ...       581       876   1813
8                 22 Piauí       13        54  ...       213       310    681
9                 23 Ceará       45       260  ...       645       902   2322
10  24 Rio Grande do Norte        5        22  ...       238       283    644
11              25 Paraíba       14        40  ...       338       634   1123
12           26 Pernambuco        6        46  ...       841      1618   2769
13              27 Alagoas       19        27  ...       345       354    857
14              28 Sergipe       14        96  ...        67       150    477
15                29 Bahia       49       226  ...      1201      1279   3362
16         31 Minas Gerais       76       518  ...      2062      3799   7343
17       32 Espírito Santo       17       192  ...       440       438   1342
18       33 Rio de Janeiro      141       534  ...      1677      3013   6088
19            35 São Paulo       86       529  ...      4854     10169  16829
20               41 Paraná      115       551  ...      1392      2206   5038
21       42 Santa Catarina       84       306  ...      1019      1199   3087
22    43 Rio Grande do Sul       42       218  ...      2267      2851   5983
23   50 Mato Grosso do Sul       47       262  ...       256       129    871
24          51 Mato Grosso       12        63  ...       207       544    892
25                52 Goiás       25        48  ...       528      1099   1855
26     53 Distrito Federal        7        55  ...       210       581    942

[27 rows x 7 columns]

In [46]:
taxa = pd.read_csv("/content/taxamortalidade.csv", encoding='ISO-8859-1', skiprows=4,skipfooter = 12, sep=";")

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  """Entry point for launching an IPython kernel.

In [53]:
taxa

      Unidade da Federação 2020/Abr 2020/Jun  ... 2021/Fev 2021/Mar  Total
0              11 Rondônia      ...      ...  ...     6,80    12,61   8,78
1                  12 Acre      ...      ...  ...     6,14     3,75   5,17
2              13 Amazonas      ...      ...  ...     8,90     5,23  11,25
3               14 Roraima      ...      ...  ...    12,21     7,38   8,73
4                  15 Pará      ...      ...  ...     5,43     3,78   4,64
5                 16 Amapá      ...      ...  ...     5,31     8,00   5,81
6             17 Tocantins      ...      ...  ...     2,95     6,70   5,74
7              21 Maranhão      ...      ...  ...     6,82     5,80   6,25
8                 22 Piauí      ...      ...  ...     5,69     3,92   4,88
9                 23 Ceará      ...      ...  ...     7,48     6,02   6,64
10  24 Rio Grande do Norte      ...      ...  ...     5,76     5,00   5,80
11              25 Paraíba      ...      ...  ...     9,96     8,10   8,42
12           26 Pernambuco      ...      ...  ...     7,91     6,65   6,89
13              27 Alagoas      ...      ...  ...    10,02     4,59   6,61
14              28 Sergipe      ...      ...  ...     3,52     5,85   6,30
15                29 Bahia      ...      ...  ...     7,11     4,80   5,72
16         31 Minas Gerais        -      ...  ...     8,42     7,62   7,87
17       32 Espírito Santo      ...      ...  ...     6,78     5,56   6,72
18       33 Rio de Janeiro   100,00        -  ...    10,86     9,15  10,43
19            35 São Paulo      ...      ...  ...     9,91     8,50   9,12
20               41 Paraná      ...        -  ...     7,86     9,00   8,44
21       42 Santa Catarina      ...      ...  ...     8,39     8,83   8,66
22    43 Rio Grande do Sul      ...      ...  ...     9,96    12,69  10,96
23   50 Mato Grosso do Sul      ...      ...  ...     5,62     3,98   6,78
24          51 Mato Grosso      ...      ...  ...     7,27     7,95   7,32
25                52 Goiás      ...      ...  ...     7,44     7,38   7,28
26     53 Distrito Federal      ...      ...  ...     5,08     6,76   5,82

[27 rows x 13 columns]

In [52]:
taxa.columns.tolist()

['Unidade da Federação',
 '2020/Abr',
 '2020/Jun',
 '2020/Jul',
 '2020/Ago',
 '2020/Set',
 '2020/Out',
 '2020/Nov',
 '2020/Dez',
 '2021/Jan',
 '2021/Fev',
 '2021/Mar',
 'Total']

In [55]:
taxa.drop(columns=['2020/Abr',
 '2020/Jun',
 '2020/Jul',
 '2020/Ago',
 '2020/Set',
 '2020/Out'],axis=1)

      Unidade da Federação 2020/Nov 2020/Dez 2021/Jan 2021/Fev 2021/Mar  Total
0              11 Rondônia     7,50     7,69     6,58     6,80    12,61   8,78
1                  12 Acre     5,88     5,70     7,27     6,14     3,75   5,17
2              13 Amazonas    11,11    10,92    23,66     8,90     5,23  11,25
3               14 Roraima    16,67     6,41     8,91    12,21     7,38   8,73
4                  15 Pará    12,80     7,95     5,08     5,43     3,78   4,64
5                 16 Amapá    33,33     8,43     3,78     5,31     8,00   5,81
6             17 Tocantins        -    11,11     3,45     2,95     6,70   5,74
7              21 Maranhão     6,11     5,59     6,97     6,82     5,80   6,25
8                 22 Piauí     9,85     7,98     6,10     5,69     3,92   4,88
9                 23 Ceará     7,58     7,16     6,49     7,48     6,02   6,64
10  24 Rio Grande do Norte    13,89     6,73     9,88     5,76     5,00   5,80
11              25 Paraíba     7,45     9,17     6,45     9,96     8,10   8,42
12           26 Pernambuco     6,06     3,65     6,66     7,91     6,65   6,89
13              27 Alagoas    16,67     6,78     8,80    10,02     4,59   6,61
14              28 Sergipe     7,57     8,16     8,51     3,52     5,85   6,30
15                29 Bahia     4,16     4,85     6,50     7,11     4,80   5,72
16         31 Minas Gerais     7,06     6,53     8,93     8,42     7,62   7,87
17       32 Espírito Santo    11,56     8,36     8,03     6,78     5,56   6,72
18       33 Rio de Janeiro    20,03    16,59    11,51    10,86     9,15  10,43
19            35 São Paulo    12,10    12,65    10,50     9,91     8,50   9,12
20               41 Paraná    12,37     8,33     7,79     7,86     9,00   8,44
21       42 Santa Catarina    16,28     9,67     7,76     8,39     8,83   8,66
22    43 Rio Grande do Sul    15,97    11,44     8,39     9,96    12,69  10,96
23   50 Mato Grosso do Sul    10,49    13,21     6,41     5,62     3,98   6,78
24          51 Mato Grosso     7,32     4,80     6,49     7,27     7,95   7,32
25                52 Goiás    11,21     4,75     6,56     7,44     7,38   7,28
26     53 Distrito Federal     8,05     4,55     4,16     5,08     6,76   5,82